### ISSUE TITLE
match_game, match_user 중복 데이터 삭제 

### ISSUE THREAD

**Issue by slbin-park** [gamemuncheol/gamemuncheol-api#141]
## Goal 

- 테이블에 game_id 가 중복으로 존재하여 삭제

## Todo 

- [ ] game_id 컬럼 삭제

**Comment by rookedsysc** [comment]
match_user에서는 match_game과 join을 위해서 필요하고 match_game에서는 user가 게임 정보를 조회할 때 캐싱되있는지 확인하기 위해서 필요합니다.
